In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import seaborn as sns

C:\Users\andriel24044\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [3]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [4]:
df = sns.load_dataset('penguins').dropna()

In [7]:
df.value_counts()

species  island     bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  sex   
Adelie   Biscoe     34.5            18.1           187.0              2900.0       Female    1
Gentoo   Biscoe     44.0            13.6           208.0              4350.0       Female    1
                    43.6            13.9           217.0              4900.0       Female    1
                    43.5            15.2           213.0              4650.0       Female    1
                                    14.2           220.0              4700.0       Female    1
                                                                                            ..
Adelie   Torgersen  36.6            17.8           185.0              3700.0       Female    1
                    36.2            17.2           187.0              3150.0       Female    1
                                    16.1           187.0              3550.0       Female    1
                    35.9            16.6           190.

In [14]:
x = torch.from_numpy(df[["bill_length_mm", "bill_depth_mm", "flipper_length_mm"]].values) 
#https://www.geeksforgeeks.org/converting-a-pandas-dataframe-to-a-pytorch-tensor/

In [15]:
x

tensor([[ 39.1000,  18.7000, 181.0000],
        [ 39.5000,  17.4000, 186.0000],
        [ 40.3000,  18.0000, 195.0000],
        [ 36.7000,  19.3000, 193.0000],
        [ 39.3000,  20.6000, 190.0000],
        [ 38.9000,  17.8000, 181.0000],
        [ 39.2000,  19.6000, 195.0000],
        [ 41.1000,  17.6000, 182.0000],
        [ 38.6000,  21.2000, 191.0000],
        [ 34.6000,  21.1000, 198.0000],
        [ 36.6000,  17.8000, 185.0000],
        [ 38.7000,  19.0000, 195.0000],
        [ 42.5000,  20.7000, 197.0000],
        [ 34.4000,  18.4000, 184.0000],
        [ 46.0000,  21.5000, 194.0000],
        [ 37.8000,  18.3000, 174.0000],
        [ 37.7000,  18.7000, 180.0000],
        [ 35.9000,  19.2000, 189.0000],
        [ 38.2000,  18.1000, 185.0000],
        [ 38.8000,  17.2000, 180.0000],
        [ 35.3000,  18.9000, 187.0000],
        [ 40.6000,  18.6000, 183.0000],
        [ 40.5000,  17.9000, 187.0000],
        [ 37.9000,  18.6000, 172.0000],
        [ 40.5000,  18.9000, 180.0000],


In [12]:
y = torch.from_numpy(df["body_mass_g"].values)

In [13]:
y

tensor([3750., 3800., 3250., 3450., 3650., 3625., 4675., 3200., 3800., 4400.,
        3700., 3450., 4500., 3325., 4200., 3400., 3600., 3800., 3950., 3800.,
        3800., 3550., 3200., 3150., 3950., 3250., 3900., 3300., 3900., 3325.,
        4150., 3950., 3550., 3300., 4650., 3150., 3900., 3100., 4400., 3000.,
        4600., 3425., 3450., 4150., 3500., 4300., 3450., 4050., 2900., 3700.,
        3550., 3800., 2850., 3750., 3150., 4400., 3600., 4050., 2850., 3950.,
        3350., 4100., 3050., 4450., 3600., 3900., 3550., 4150., 3700., 4250.,
        3700., 3900., 3550., 4000., 3200., 4700., 3800., 4200., 3350., 3550.,
        3800., 3500., 3950., 3600., 3550., 4300., 3400., 4450., 3300., 4300.,
        3700., 4350., 2900., 4100., 3725., 4725., 3075., 4250., 2925., 3550.,
        3750., 3900., 3175., 4775., 3825., 4600., 3200., 4275., 3900., 4075.,
        2900., 3775., 3350., 3325., 3150., 3500., 3450., 3875., 3050., 4000.,
        3275., 4300., 3050., 4000., 3325., 3500., 3500., 4475., 

In [9]:
class MLP(nn.Module):
    def __init__(self, num_dados_entrada, neuronios_c1, neuronios_c2, num_targets):
        super().__init__()
        
        self.camadas = nn.Sequential(
            nn.Linear(num_dados_entrada, neuronios_c1),
            nn.Sigmoid(),
            nn.Linear(neuronios_c1, neuronios_c2),
            nn.Sigmoid(),
            nn.Linear(neuronios_c2, num_targets),
        )
        
    def forward(self, x):
        x = self.camadas(x)
        return x

In [ ]:
NUM_DADOS_DE_ENTRADA = 3  
NUM_DADOS_DE_SAIDA = 1  
NEURONIOS_C1 = 3
NEURONIOS_C2 = 2

minha_mlp = MLP(
    NUM_DADOS_DE_ENTRADA, NEURONIOS_C1, NEURONIOS_C2, NUM_DADOS_DE_SAIDA
)

In [ ]:
y_prev = minha_mlp(x)
y_prev

tensor([[0.1061],
        [0.1029],
        [0.0728],
        [0.1014],
        [0.1145]], grad_fn=<AddmmBackward0>)

In [ ]:
TAXA_DE_APRENDIZADO = 0.001

otimizador = optim.SGD(minha_mlp.parameters(), lr=TAXA_DE_APRENDIZADO)

In [ ]:
fn_perda = nn.MSELoss()

In [ ]:
#definir x_teste e y_teste por split



In [ ]:
NUM_EPOCAS = 100

minha_mlp.train()

fator_de_parada = 5 

melhora_minima = 0.01 

contador_de_parada = 0

melhor_perda = float('inf')

for epoca in range(NUM_EPOCAS):
    # forward pass
    y_pred = minha_mlp(x)

    # zero grad
    otimizador.zero_grad()

    # loss
    loss = fn_perda(y_true.view(-1, 1), y_pred.view(-1, 1))

    # backpropagation
    loss.backward()

    # atualiza parâmetros
    otimizador.step()

    # mostra resultado (opcional)
    #print(epoca, loss.data)

    minha_mlp.eval()
    val_loss = 0
    with torch.no_grad():
        for x_val, y_val in zip(x_teste, y_teste.view(-1, 1)):
            y_pred = minha_mlp(x_val)
            val_loss += fn_perda(y_val, y_pred).item()

    val_loss /= len(y_teste)
    minha_mlp.train()

    if val_loss < melhor_perda - melhora_minima:
        melhor_perda = val_loss
        contador_de_parada = 0
    else:
        contador_de_parada += 1
        if contador_de_parada == fator_de_parada:
            print(f"Parada antecipada na epoca: {epoca}")
            break

Parada antecipada na epoca: 5


In [ ]:
for i in minha_mlp.parameters():
    print(i)

Parameter containing:
tensor([[ 0.5643,  0.2875, -0.3485],
        [ 0.1628, -0.2300, -0.4823],
        [-0.0060,  0.3922,  0.3357]], requires_grad=True)
Parameter containing:
tensor([ 0.3879, -0.5174, -0.1784], requires_grad=True)
Parameter containing:
tensor([[ 0.5584,  0.5340,  0.0956],
        [-0.1686,  0.2619,  0.2142]], requires_grad=True)
Parameter containing:
tensor([0.3888, 0.1350], requires_grad=True)
Parameter containing:
tensor([[ 0.6983, -0.3243]], requires_grad=True)
Parameter containing:
tensor([-0.2404], requires_grad=True)


In [ ]:
minha_mlp.eval()

MLP(
  (camadas): Sequential(
    (0): Linear(in_features=3, out_features=3, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=3, out_features=2, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=2, out_features=1, bias=True)
  )
)

In [ ]:
with torch.no_grad():
    y_pred = minha_mlp(x_teste)

In [ ]:
y_pred

tensor([[0.1127],
        [0.0944]])

In [ ]:
from sklearn.metrics import mean_squared_error

RMSE = mean_squared_error(y_teste, y_pred, squared=False)
print(RMSE)

0.49171427


### Referências

https://cyborgcodes.medium.com/what-is-early-stopping-in-deep-learning-eeb1e710a3cf
https://www.deeplearningbook.com.br/usando-early-stopping-para-definir-o-numero-de-epocas-de-treinamento/